# Generated by Django 6.1 on 2026-08-27 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_payment_status'),
        ('licensing', '0004_plan_max_daily_forwards_forwardingusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='licensing.plan'),
        ),
    ]
