# Generated by Django 6.1 on 2026-08-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_telegramconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramconnection',
            name='encrypted_session',
            field=models.TextField(blank=True),
        ),
    ]
