# Generated by Django 6.1 on 2026-08-26 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForwardedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_chat_id', models.BigIntegerField()),
                ('source_message_id', models.BigIntegerField()),
                ('destination_chat_id', models.BigIntegerField()),
                ('forwarded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forwarded_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'source_chat_id', 'source_message_id', 'destination_chat_id'), name='unique_user_forwarded_message')],
            },
        ),
    ]
