# Generated by Django 6.1 on 2026-09-04 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forwarding', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForwardingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_chat_id', models.BigIntegerField()),
                ('destination_chat_id', models.BigIntegerField()),
                ('source_message_id', models.BigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forwarding_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'status'], name='forwarding__user_id_fb57d9_idx'), models.Index(fields=['created_at'], name='forwarding__created_bd21a8_idx'), models.Index(fields=['source_chat_id'], name='forwarding__source__445f02_idx'), models.Index(fields=['destination_chat_id'], name='forwarding__destina_69aba5_idx')],
            },
        ),
    ]
