# Generated by Django 6.1 on 2026-09-02 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForwardingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('keywords', models.TextField(blank=True)),
                ('blocked_keywords', models.TextField(blank=True)),
                ('allow_text', models.BooleanField(default=True)),
                ('allow_photos', models.BooleanField(default=True)),
                ('allow_videos', models.BooleanField(default=True)),
                ('allow_documents', models.BooleanField(default=True)),
                ('allow_audio', models.BooleanField(default=True)),
                ('allow_forwarded', models.BooleanField(default=True)),
                ('allow_normal', models.BooleanField(default=True)),
                ('filter_captions', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel_pair', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forwarding_rule', to='channels.channelpair')),
            ],
        ),
    ]
