# Generated by Django 6.1 on 2026-09-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_forwardingrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelpair',
            name='message_limit',
            field=models.PositiveIntegerField(default=0, help_text='Maximum messages to forward for this channel pair. 0 means no pair-specific limit.'),
        ),
    ]
